# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f7f6487053a535d11eb7b56c8d5e8a8bcdedd448b3dbf698dbbdcf77730f25d9faafca914c2d33e8b14b831548aac549236472768150d2c58f57ee776d88b13

test:
  secret_key_base: 39f5210d75b9cb786c4ed061b64e25aef281d2ff6ca2fed30d167803ad79dd0e2294d413b0351ea2294e5586bc6a9c36bfd79261c5c23c0335f22ffc77164573

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
